'Alt + D za prikaz
@startuml classdiag

interface UserDetails {
    # getUsername() : String
    # getPassword() : String
    # getGetAuthorities() : <GrantedAuthority>
    # isNonExpired(): Boolean
    # isNonLocked(): Boolean
    # isCredentialsNonExpired(): Boolean
    # isEnabled(): Boolean
}

class UserRole <<Enumeration>> {
    ADMIN
    PROFESSOR
    STUDENT
}

abstract class AbstractUser {
    ID : UUID
    email : String
    password : String
    role : UserRole
    firstName : String
    lastName : String
    phoneNumber : String
    credentialsUpdatedAt : Date
    enabled : Boolean
    locked : Boolean

    # getUsername() : String
    # getPassword() : String
    # getGetAuthorities() : <GrantedAuthority>
    # isNonExpired(): Boolean
    # isNonLocked(): Boolean
    # isCredentialsNonExpired(): Boolean
    # isEnabled(): Boolean
}

class Student {
  
}

class Professor {
  
}


class Admin {
  
}

UserDetails <|-- AbstractUser
UserRole <|- AbstractUser
AbstractUser <|--- Student
AbstractUser <|--- Professor
AbstractUser <|- Admin

class College {
    Name : String
}

class Subject {
    Name : String
}

class Grade {
    Value : Int
    Date : Date
}

College "1" -- "*" Subject : contains
Professor "*" ---- "*" Subject : teaches
Subject "*" --- "*" Student : attends
Grade "*" - "1" Student : receive
Grade "*" - "1" Subject : is from

class Noticeboard {

}

class NoticeboardItemCategory <<Enumaration>> {
    UNIVERSITY_ANNOUNCEMENT
    UNIVERSITY_GUEST_ANNOUNCEMENT
    COLLEGE_ANNOUCEMENT
    COLLEGE_GUEST_ANNOUCEMENT
    SUBJECT_ANNOUCEMENT
    SUBJECT_EXAM_RESULT_ANNOUCEMENT
    SUBJECT_EXAM_DATE_ANNOUNCEMENT
    INTERNSHIP_ANNOUNCEMENT
    ACTIVITIES_ANNOUNCEMENT
}

class NoticeboardItem {
    Title : String
    Message : String
    UpdatedAt : DateTime
    Category : NoticeboardItemCategory
}

Noticeboard "1" *- "*" NoticeboardItem : contains
Noticeboard "0" -----o "1" College : contains
NoticeboardItem "*" --- "0..1" Subject : might be about
NoticeboardItemCategory <|-- NoticeboardItem
class Calendar {

}

class CalendarItem {
    Title : String
    Start : DateTime
}

Calendar "1" *- "*" CalendarItem
Calendar "*" -o "1" College : contains
CalendarItem "*" ---- "0..1" Subject : might be about

class Repository {

}

class RepositoryItem {
    Name : String
    ShortDescription : DateTime
    URL: String
}

Repository "1" *- "*" RepositoryItem
Repository "*" ---o "1" College : contains
RepositoryItem "*" --- "0..1" Subject : might be about


class FAQ {

}

class FAQItem {
    Title : String
    Message : String
    UpdatedAt : DateTime
}

FAQ "*" -----o "1" College : contains
FAQ "1" *- "*" FAQItem
@enduml